### ISSUE TITLE
FYI: Alternative approach to automating Power Query

### ISSUE THREAD

**Issue by sio** [metamoof/powershell-powerbidesktop#13]
I have discovered the project - [PowerQueryNet](https://github.com/gsimardnet/PowerQueryNet) - that takes another approach to automating PowerQuery execution.

It relies on the .NET libraries from [PowerQuery SDK](https://marketplace.visualstudio.com/items?itemName=Dakahn.PowerQuerySDK) to execute Power Query code in-process instead of offloading it to the PowerBI Desktop instance.

I'm not sure how that interaction happens exactly, but I hope the project's author [will clarify](https://github.com/gsimardnet/PowerQueryNet/issues/3) that soon.

I thought you might find this information useful.

**Comment by metamoof** [comment]
Thanks.

I've [added my own question](https://github.com/gsimardnet/PowerQueryNet/issues/1#issuecomment-418856411) to another issue.
